application: tvpictionary2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /tv
  static_dir: tv

- url: /mobile
  static_dir: mobile
  
- url: /libs
  static_dir: libs  

- url: /js
  static_dir: js 

- url: /css
  static_dir: css 

- url: /images
  static_dir: images
  
- url: /.*
  script: backend.main.app


libraries :
- name: webapp2
  version: latest

inbound_services:
- channel_presence