application: tvpictionary2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /tv
  static_dir: tv/static/

- url: /mobile
  static_dir: mobile/static/

- url: /common
  static_dir: common/static
  
- url: /.*
  script: Main.app


libraries :
- name: webapp2
  version: latest
